#! /bin/sh
set -e
DIR="/etc/oa-indicator /var/log/oa-indicator /var/lib/oa-indicator /var/run/oa-indicator"
case "$1" in
    configure)
        if ! grep oa-indicator /etc/group > /dev/null
        then
            addgroup oa-indicator
        fi
        chgrp -R oa-indicator $DIR
        chmod 2775 $DIR
        find /var/lib/oa-indicator/ -type d | xargs chgrp oa-indicator
        find /var/lib/oa-indicator/ -type d | xargs chmod 2775
        if [ -d /san -a -d /var/lib/oa-indicator ]
        then
            if [ ! -e /san/oa-indicator ]
            then
                mv /var/lib/oa-indicator /san/
                ln -s /san/oa-indicator /var/lib/oa-indicator
            fi
        fi
        chown nagios /var/lib/oa-indicator/nagios
        chown nagios:nagios /usr/sbin/oa-indicator-status
        touch /var/log/oa-indicator/status.log
        chown nagios /var/log/oa-indicator/status.log
        chmod 664 /var/log/oa-indicator/status.log
        if ! diff -q /var/lib/oa-indicator/cgi/ws /tmp/liboa-indicator-perl.ws > /dev/null
        then
            echo 'web service updated, restarting apache'
            /etc/init.d/apache2 restart
        else
            if ! diff -q /usr/share/perl5/OA/Indicator/WS.pm /tmp/liboa-indicator-perl.WS.pm > /dev/null
            then
                echo 'web service library updated, restarting apache'
                /etc/init.d/apache2 restart
            fi
        fi
        rm -f /tmp/liboa-indicator-perl.ws /tmp/liboa-indicator-perl.WS.pm
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0


